name: Deploy Frontend to Droplet

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Setup git config
      - name: setup git config
        run: |
          git config user.name "Github Actions Bot"  
          git config user.email "<>"

      # Install dependencies
      - name: Install Dependencies
        run: npm install --force

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Build Docker image
      - name: Build Docker Image
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then  
            docker build --tag customvivint-front-wizard .  
            docker tag customvivint-front-wizard ${{ secrets.DOCKERHUB_USERNAME }}/customvivint-front-wizard:latest  
          elif [[ ${{ github.ref }} == 'refs/heads/develop' ]]; then  
            docker build --tag customvivint-front-wizard-staging .  
            docker tag customvivint-front-wizard-staging ${{ secrets.DOCKERHUB_USERNAME }}/customvivint-front-wizard-staging:latest  
          fi

      # Push Docker image
      - name: Push Docker Image
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then  
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/customvivint-front-wizard:latest  
          elif [[ ${{ github.ref }} == 'refs/heads/develop' ]]; then  
            docker push ${{ secrets.DOCKERHUB_USERNAME }}/customvivint-front-wizard-staging:latest  
          fi

      # SSH to Droplet and Update Container
      - name: SSH to Droplet and Update Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: root
          password: ${{ secrets.DROPLET_PASSWORD }}
          port: 22
          script: |
            if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then  
              docker stop customvivint-front-wizard || true  
              docker rm customvivint-front-wizard || true  
              docker pull ${{ secrets.DOCKERHUB_USERNAME }}/customvivint-front-wizard:latest  
              docker run -d --name customvivint-front-wizard -p 3002:80 ${{ secrets.DOCKERHUB_USERNAME }}/customvivint-front-wizard:latest  
            elif [[ ${{ github.ref }} == 'refs/heads/develop' ]]; then  
              docker stop customvivint-front-wizard-staging || true
              docker rm customvivint-front-wizard-staging || true  
              docker pull ${{ secrets.DOCKERHUB_USERNAME }}/customvivint-front-wizard-staging:latest  
              docker run -d --name customvivint-front-wizard-staging -p 3003:80 ${{ secrets.DOCKERHUB_USERNAME }}/customvivint-front-wizard-staging:latest  
            fi
